config/routes.rb
Rails.application.routes.draw do
  root 'websites#index'

  resources :websites, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/website.rb
class Website < ApplicationRecord
  scope :active, -> { where(active: true) }
  scope :desktop_asc, -> { active.order(desktop_score: :asc) }
  scope :desktop_desc, -> { active.order(desktop_score: :desc) }
  scope :mobile_asc, -> { active.order(mobile_score: :asc) }
  scope :mobile_desc, -> { active.order(mobile_score: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  def index
    @websites = case params['sort']
                when 'mobile_desc'
                  Website.mobile_desc
                when 'desktop_asc'
                  Website.desktop_asc
                when 'desktop_desc'
                  Website.desktop_desc
                else
                  Website.mobile_desc
                end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    case params['sort']
    when 'mobile_asc'
      @websites = Website.mobile_asc
    when 'mobile_desc'
      @websites = Website.mobile_desc
    when 'desktop_asc'
      @websites = Website.desktop_asc
    when 'desktop_desc'
      @websites = Website.desktop_desc
    else
      @websites = Website.all
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XypnSeo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/websites/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-sm-12 text-center">
      <h1>XYPN Scraper</h1>
    </div>

    <div class="col-sm-6 col-sm-offset-3 text-center">
      <p>
        The desktop and mobile scores listed are calculated by Google's PageSpeed Insights 
        and represent a website's overall speed and performance. A higher score is better 
        and a score of 85 or above indicates that the page is performing well.
      </p>
      <p>
        PageSpeed Insights analyzes a page to see if it follows Google's recommendations for 
        making a page render in under a second. Research has shown that any delay longer than 
        a second will cause the user to interrupt their flow of thought, creating a poor 
        experience. 
      </p>
      <p>
        If you are intersted to learn more about why page speed is important,
        <a href="https://www.doubleclickbygoogle.com/articles/mobile-speed-matters/" target="_blank">
          click here.
        </a>
      </p>
    </div>

  <end>

  <div class="row">
    <div class="col-sm-12">

      <table class="table table-striped table-condensed">
        <tr>
          <th>Advisor</th>
          <th>Business</th>
          <th>XYPN Profile</th>
          <th>Website</th>
          <th>
            Desktop
            <%= link_to "&#8593".html_safe, websites_path(sort: 'desktop_asc') %>
            <%= link_to "&#8595".html_safe, websites_path(sort: 'desktop_desc') %>
          </th>
          <th>
            Mobile
            <%= link_to "&#8593".html_safe, websites_path(sort: 'mobile_asc') %>
            <%= link_to "&#8595".html_safe, websites_path(sort: 'mobile_desc') %>
          </th>
        </tr>

        <% @websites.each do | website | %>
          <tr>
            <td><%= website.advisor %></td>
            <td><%= website.business %></td>
            <td><%= link_to "Profile", website.xypn_profile, :target => '_blank' %></td>
            <td><%= link_to "#{website.url}", website.url, :target => '_blank' %></td>
            <td><%= website.desktop_score %></td>
            <td><%= website.mobile_score %></td>
          </tr>
        <% end %>
      </table>

    <end><!-- col-sm-12 -->
  <end><!-- row -->
<end><!-- container -->

app/views/welcome/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-sm-12 text-center">
      <h1>XYPN Scraper</h1>
    </div>

  <end>

  <div class="row">
    <div class="col-sm-12">

      <table class="table table-striped table-condensed">
        <tr>
          <th>Advisor</th>
          <th>Business</th>
          <th>XYPN Profile</th>
          <th>Website</th>
          <th>
            Desktop
            <%= link_to "&#8593".html_safe, root_path(sort: 'desktop_asc') %>
            <%= link_to "&#8595".html_safe, root_path(sort: 'desktop_desc') %>
          </th>
          <th>
            Mobile
            <%= link_to "&#8593".html_safe, root_path(sort: 'mobile_asc') %>
            <%= link_to "&#8595".html_safe, root_path(sort: 'mobile_desc') %>
          </th>
        </tr>

        <% @websites.each do | website | %>
          <tr>
            <td><%= website.advisor %></td>
            <td><%= website.business %></td>
            <td><%= link_to "Profile", website.xypn_profile, :target => '_blank' %></td>
            <td><%= link_to "#{website.url}", website.url, :target => '_blank' %></td>
            <td><%= website.desktop_score %></td>
            <td><%= website.mobile_score %></td>
          </tr>
        <% end %>
      </table>

    <end><!-- col-sm-12 -->
  <end><!-- row -->
<end><!-- container -->